#cloud-config
package_upgrade: true
packages:
  - curl
  - git
  - install
  - ca-certificates
  - gnupg
  - lsb-release
  - jq
runcmd:
  # Installing azure cli
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  
  # Install SQL Server tools
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
  - sudo apt-get update 
  - sudo apt-get install mssql-tools unixodbc-dev
  - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
